version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/quilldeck.db
    volumes:
      - ./data:/app/data
    networks:
      - quilldeck-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - quilldeck-network
    depends_on:
      - backend

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: quilldeck
      POSTGRES_USER: quilldeck
      POSTGRES_PASSWORD: quilldeck123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quilldeck-network

volumes:
  postgres_data:

networks:
  quilldeck-network:
    driver: bridge